const mongoose = require('mongoose')
const dashBoardSchema = new mongoose.Schema({
    date:{
        type:Date
    },
    totalRecovered:{
        type:Number
    },
    totalDeaths:{
        type:Number
    },
    totalActiveCases:{
        type:Number
    },
    districtTotals:{
        Gampaha:{
            type:Number,
            default:0
        },
        Colombo:{
            type:Number,
            default:0
        },
        Kalutara:{
            type:Number,
            default:0
        },
        Puttalam:{
            type:Number,
            default:0
        },
        Kurunagala:{
            type:Number,
            default:0
        },
        Kandy:{
            type:Number,
            default:0
        },
        Matale:{
            type:Number,
            default:0
        },
        NuwaraEliya:{
            type:Number,
            default:0
        },
        Kegalle:{
            type:Number,
            default:0
        },
        Ratnapura:{
            type:Number,
            default:0
        },
        Hambantota:{
            type:Number,
            default:0
        },
        Matara:{
            type:Number,
            default:0
        },
        Galle:{
            type:Number,
            default:0
        },
        Badulla:{
            type:Number,
            default:0
        },
        Monaragala:{
            type:Number,
            default:0
        },
        Trincomalee:{
            type:Number,
            default:0
        },
        Batticaloa:{
            type:Number,
            default:0
        },
        Ampara:{
            type:Number,
            default:0
        },
        Anaradhapura:{
            type:Number,
            default:0
        },
        Polonnaruwa:{
            type:Number,
            default:0
        },
        Jaffna:{
            type:Number,
            default:0
        },
        Kilinochchi:{
            type:Number,
            default:0
        },
        Mannar:{
            type:Number,
            default:0
        },
        Mullaitivu:{
            type:Number,
            default:0
        },
        Vavuniya:{
            type:Number,
            default:0
        }
    },
    dailyRecovered:{
        Gampaha:{
            type:Number,
            default:0
        },
        Colombo:{
            type:Number,
            default:0
        },
        Kalutara:{
            type:Number,
            default:0
        },
        Puttalam:{
            type:Number,
            default:0
        },
        Kurunagala:{
            type:Number,
            default:0
        },
        Kandy:{
            type:Number,
            default:0
        },
        Matale:{
            type:Number,
            default:0
        },
        NuwaraEliya:{
            type:Number,
            default:0
        },
        Kegalle:{
            type:Number,
            default:0
        },
        Ratnapura:{
            type:Number,
            default:0
        },
        Hambantota:{
            type:Number,
            default:0
        },
        Matara:{
            type:Number,
            default:0
        },
        Galle:{
            type:Number,
            default:0
        },
        Badulla:{
            type:Number,
            default:0
        },
        Monaragala:{
            type:Number,
            default:0
        },
        Trincomalee:{
            type:Number,
            default:0
        },
        Batticaloa:{
            type:Number,
            default:0
        },
        Ampara:{
            type:Number,
            default:0
        },
        Anaradhapura:{
            type:Number,
            default:0
        },
        Polonnaruwa:{
            type:Number,
            default:0
        },
        Jaffna:{
            type:Number,
            default:0
        },
        Kilinochchi:{
            type:Number,
            default:0
        },
        Mannar:{
            type:Number,
            default:0
        },
        Mullaitivu:{
            type:Number,
            default:0
        },
        Vavuniya:{
            type:Number,
            default:0
        }
    },
    dailyDeaths:{
        Gampaha:{
            type:Number,
            default:0
        },
        Colombo:{
            type:Number,
            default:0
        },
        Kalutara:{
            type:Number,
            default:0
        },
        Puttalam:{
            type:Number,
            default:0
        },
        Kurunagala:{
            type:Number,
            default:0
        },
        Kandy:{
            type:Number,
            default:0
        },
        Matale:{
            type:Number,
            default:0
        },
        NuwaraEliya:{
            type:Number,
            default:0
        },
        Kegalle:{
            type:Number,
            default:0
        },
        Ratnapura:{
            type:Number,
            default:0
        },
        Hambantota:{
            type:Number,
            default:0
        },
        Matara:{
            type:Number,
            default:0
        },
        Galle:{
            type:Number,
            default:0
        },
        Badulla:{
            type:Number,
            default:0
        },
        Monaragala:{
            type:Number,
            default:0
        },
        Trincomalee:{
            type:Number,
            default:0
        },
        Batticaloa:{
            type:Number,
            default:0
        },
        Ampara:{
            type:Number,
            default:0
        },
        Anaradhapura:{
            type:Number,
            default:0
        },
        Polonnaruwa:{
            type:Number,
            default:0
        },
        Jaffna:{
            type:Number,
            default:0
        },
        Kilinochchi:{
            type:Number,
            default:0
        },
        Mannar:{
            type:Number,
            default:0
        },
        Mullaitivu:{
            type:Number,
            default:0
        },
        Vavuniya:{
            type:Number,
            default:0
        }
    },
    dailyActiveCases:{
        Gampaha:{
            type:Number,
            default:0
        },
        Colombo:{
            type:Number,
            default:0
        },
        Kalutara:{
            type:Number,
            default:0
        },
        Puttalam:{
            type:Number,
            default:0
        },
        Kurunagala:{
            type:Number,
            default:0
        },
        Kandy:{
            type:Number,
            default:0
        },
        Matale:{
            type:Number,
            default:0
        },
        NuwaraEliya:{
            type:Number,
            default:0
        },
        Kegalle:{
            type:Number,
            default:0
        },
        Ratnapura:{
            type:Number,
            default:0
        },
        Hambantota:{
            type:Number,
            default:0
        },
        Matara:{
            type:Number,
            default:0
        },
        Galle:{
            type:Number,
            default:0
        },
        Badulla:{
            type:Number,
            default:0
        },
        Monaragala:{
            type:Number,
            default:0
        },
        Trincomalee:{
            type:Number,
            default:0
        },
        Batticaloa:{
            type:Number,
            default:0
        },
        Ampara:{
            type:Number,
            default:0
        },
        Anaradhapura:{
            type:Number,
            default:0
        },
        Polonnaruwa:{
            type:Number,
            default:0
        },
        Jaffna:{
            type:Number,
            default:0
        },
        Kilinochchi:{
            type:Number,
            default:0
        },
        Mannar:{
            type:Number,
            default:0
        },
        Mullaitivu:{
            type:Number,
            default:0
        },
        Vavuniya:{
            type:Number,
            default:0
        }
    }
})

dashBoardSchema.pre('save',function(next){
    console.log(this)
    // console.log(this)
    next()
})
const DashBoard = mongoose.model('DashBoard',dashBoardSchema)
module.exports=DashBoard